#!/usr/bin/env bash
# Author: Goldie Lin
# Description: BASH-ish directory traversal.
# Currect purposes:
#   * Ignored all files, just check the directories.
#   * Traversal the whole directory structure.
#   * Find out all the leaf and non-leaf directories. (Printed)
# References:
#   [1] http://mywiki.wooledge.org/ArithmeticExpression

set -euo pipefail

# Variable definitions
# ====================

# color code
declare -grx cClean=$'\e[0m'
declare -grx cBlack=$'\e[30m'
declare -grx cDarkRed=$'\e[31m'
declare -grx cDarkGreen=$'\e[32m'
declare -grx cDarkYellow=$'\e[33m'
declare -grx cDarkBlue=$'\e[34m'
declare -grx cDarkPurple=$'\e[35m'
declare -grx cDarkCyan=$'\e[36m'
declare -grx cLightGray=$'\e[37m'
declare -grx cGray=$'\e[30;1m'
declare -grx cRed=$'\e[31;1m'
declare -grx cGreen=$'\e[32;1m'
declare -grx cYellow=$'\e[33;1m'
declare -grx cBlue=$'\e[34;1m'
declare -grx cPurple=$'\e[35;1m'
declare -grx cCyan=$'\e[36;1m'
declare -grx cWhite=$'\e[37;1m'

# Function definitions
# ====================

# if it has any subdir, then return zero (true), otherwise non-zero (false).
#has_subdir() {
#  local -r path="$1"
#  local -r subdir_count="$(find "${path}" -mindepth 1 -maxdepth 1 -type d | wc -l)" # default find won't follow symlinks, unless "-L" option
#  test "${subdir_count}" -gt 0
#}

# down search recursively, likes dfs.
down_search() {
  local -r lvl="$1"
  local -r path="$2"
  local -i i=0
  local -a subdirs=()
  local j=""

  [[ ! -d "${path}" ]] &&  (echo "Error: '${path}' shall be a directory!" >&2 && return 1)

  while IFS= read -r -d $'\0' j; do
    subdirs[i++]="$j" # array indices are numeric context, will force arithmetic evaluation [1]
  done < <(find "${path}" -mindepth 1 -maxdepth 1 -type d -print0) # default find won't follow symlinks, unless "-L" option

  #local -r rst_dotglob="$(shopt -p dotglob)" || true # Get restoration command
  #shopt -s dotglob # Set shell option
  #for j in "${path}"/*; do
  #  [[ -d "$j" && ! -L "$j" ]] && subdirs[i++]="$j" # array indices are numeric context, will force arithmetic evaluation [1]
  #done
  #${rst_dotglob} # Restore shell option

  #if has_subdir "$path"; then
  if [[ "${#subdirs[@]}" -gt 0 ]]; then
    echo "[${cDarkCyan}${lvl}${cClean}][${cDarkGreen}non-leaf${cClean}] '${path}' ${cDarkGreen}(${#subdirs[@]})${cClean}"
    for ((i=0; i<${#subdirs[@]}; i++)); do
      down_search "$(( lvl+1 ))" "${subdirs[$i]}"
    done
  else
    echo "[${cDarkCyan}${lvl}${cClean}][${cDarkYellow}leaf-dir${cClean}] '${path}'"
  fi
}

main() {
  local -r dest="${1:-"."}"

  down_search 0 "${dest}"
}

main "$@"
