#!/usr/bin/env bash
# Author: Goldie Lin
# Usage: cd to Android root and run this script.

set -o errexit
set -o pipefail
set -o nounset

# Variable definitions
# ====================

readonly def_file="build/core/definitions.mk"
readonly top_file="build/core/envsetup.mk"

# Function definitions
# ====================

check_pwd() {
  if [[ ! -f "${top_file}" ]]; then
    echo >&2 "Error: Please cd to Android root and run again."
    return 1
  fi
}

gen_def_list() {
  local def_list=""

  def_list="$(grep '^define' "${def_file}" | cut -d' ' -f2- | sort -u)"
  echo "${def_list}"
}

main() {
  check_pwd
  gen_def_list
}

main "$@"
