#!/usr/bin/env bash
# Author: Goldie Lin
# Usage: cd to Android root and run this script.

set -euo pipefail

# Variable definitions
# ====================

declare -gr def_file="build/core/definitions.mk"
declare -gr def_file2="build/make/core/definitions.mk"
declare -gr top_file="build/core/envsetup.mk"
declare -gr top_file2="build/make/core/envsetup.mk"

# Function definitions
# ====================

check_pwd() {
  if [[ ! -f "${top_file}" && ! -f "${top_file2}" ]]; then
    echo "Error: Please cd to Android root and run again." >&2
    return 1
  fi
}

gen_def_list() {
  local def_list=""

  if [[ -f "${def_file}" ]]; then
    def_list="$(grep '^define' "${def_file}" | cut -d' ' -f2- | sort -u)"
  elif [[ -f "${def_file2}" ]]; then
    def_list="$(grep '^define' "${def_file2}" | cut -d' ' -f2- | sort -u)"
  fi
  echo "${def_list}"
}

main() {
  check_pwd
  gen_def_list
}

main "$@"
