#!/usr/bin/env bash
# Author: Goldie Lin
# Description: Traversal of all *included* DTSI for a specific Linux kernel DTS.
# Usage: cd /path/to/dts && run ./kernel-dtsi-traversal <filename.dts>

set -euo pipefail

# Function definitions
# ====================

expand_lvl_to_indents() {
  local -i lvl="$1"
  local -i i=0

  for ((i=0; i<lvl; i++)); do
    echo -n "  "  # one indent = two space.
  done
}

# down search recursively, likes dfs.
down_search() {
  local -r lvl="$1"
  local -r parent="$2"
  local -i i=0
  local -a children=()
  local j=""

  [[ ! -f "${parent}" ]] &&  (echo >&2 "Error: '${parent}' does not existed!" && return 1)

  while IFS= read -r j; do
    children[i++]="$j" # array indices are numeric context, will force arithmetic evaluation [1]
  done < <(grep -P '^\s*(#include)\s+' "${parent}" | grep -Po '(?<=")([^"]+)(?=")')

  if [[ "${#children[@]}" -gt 0 ]]; then
    echo "$(expand_lvl_to_indents "$lvl")* ${parent}"  # (${#children[@]})"
    for ((i=0; i<${#children[@]}; i++)); do
      down_search "$(( lvl+1 ))" "${children[$i]}"
    done
  else
    echo "$(expand_lvl_to_indents "$lvl")* ${parent}"
  fi
}

main() {
  local -r dest="$1"

  down_search 0 "${dest}"
}

main "$@"
